trigger:
  - "*"

variables:
  buildConfiguration: "Release"
  dotnetSdkVersion: "8.x" # Updated to .NET 6.x for compatibility with Azure Functions
  functionAppName: "$(LeaderboardAppName)" # Make sure this variable is set properly in your environment

stages:
  - stage: "Build"
    displayName: "Build the web application"
    jobs:
      - job: "Build"
        displayName: "Build job"
        pool:
          name: "davinceleecode-remote-agent"
          demands:
            - npm

        variables:
          wwwrootDir: "Tailspin.SpaceGame.Web/wwwroot"

        steps:
          # Install the correct .NET SDK version
          - task: UseDotNet@2
            displayName: "Use .NET SDK $(dotnetSdkVersion)"
            inputs:
              version: "$(dotnetSdkVersion)"

          - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
            displayName: "Write build info"
            workingDirectory: $(wwwrootDir)

          # Restore dependencies
          - task: DotNetCoreCLI@2
            displayName: "Restore project dependencies"
            inputs:
              command: "restore"
              projects: "**/*.csproj"

          # Build the project
          - task: DotNetCoreCLI@2
            displayName: "Build the project - $(buildConfiguration)"
            inputs:
              command: "build"
              arguments: "--no-restore --configuration $(buildConfiguration)"
              projects: "**/*.csproj"

          # Publish the project
          - task: DotNetCoreCLI@2
            displayName: "Publish the project - $(buildConfiguration)"
            inputs:
              command: "publish"
              projects: "**/*.csproj"
              publishWebProjects: false
              arguments: "--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)"
              zipAfterPublish: true

          # Publish the artifact
          - publish: "$(Build.ArtifactStagingDirectory)"
            artifact: drop

  - stage: "Deploy"
    displayName: "Deploy the web application"
    dependsOn: Build
    jobs:
      - deployment: Deploy
        pool:
          name: "davinceleecode-remote-agent"
        environment: spike
        variables:
          - group: Release
        strategy:
          runOnce:
            deploy:
              steps:
                # Download build artifact
                - download: current
                  artifact: drop

                # Deploy Web App to Azure
                - task: AzureWebApp@1
                  displayName: "Azure App Service Deploy: website"
                  inputs:
                    azureSubscription: "Resource Manager - Tailspin - Space Game"
                    appName: "$(WebAppName)"
                    appType: webAppLinux
                    package: "$(Pipeline.Workspace)/drop/$(buildConfiguration)/Tailspin.SpaceGame.Web.zip"

                # Deploy Azure Function App to Azure
                - task: AzureFunctionApp@1
                  displayName: "Azure Function Deploy: leaderboard"
                  inputs:
                    azureSubscription: "Resource Manager - Tailspin - Space Game"
                    appType: functionAppLinux
                    appName: "$(LeaderboardAppName)"
                    package: "$(Pipeline.Workspace)/drop/$(buildConfiguration)/Tailspin.SpaceGame.LeaderboardFunction.zip"
                    runtimeStack: "DOTNET|8" # Set runtime stack for .NET 8
                    startUpCommand: ""

                # Update App Settings to link to Azure Function
                - task: AzureAppServiceSettings@1
                  displayName: "Update web app settings"
                  inputs:
                    azureSubscription: "Resource Manager - Tailspin - Space Game"
                    appName: $(WebAppName)
                    resourceGroupName: $(ResourceGroupName)
                    appSettings: |
                      [
                        {
                          "name": "AppSettings__LeaderboardFunctionUrl",
                          "value": "http://$(LeaderboardAppName).azurewebsites.net/api/LeaderboardFunction",
                          "slotSetting": false
                        }
                      ]
